blank_issues_enabled: true
contact_links:
  - name: Feature Requests
    url: https://woocommerce.com/feature-requests/woocommerce/
    about: If you have an idea for a new feature that you wished existed in WooCommerce, take a look at our Feature Requests and vote, or open a new Feature Request yourself!
  
